version: "3.8"

services:
  rtl-sdr:
    build:
      context: ./services/sdr
      dockerfile: Dockerfile
    container_name: satx-rtl
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    ports:
      - "1234:1234"  # rtl_tcp
    volumes:
      - ./recordings:/recordings
      - ./configs:/configs:ro
    environment:
      - RTL_SAMPLE_RATE=2400000
      - RTL_GAIN=49
    restart: unless-stopped
    networks:
      - satx-network

  processor:
    build:
      context: ./services/ml
      dockerfile: Dockerfile
    container_name: satx-processor
    volumes:
      - ./recordings:/app/recordings
      - ./logs:/app/logs
      - ./models:/app/models:ro
      - ./configs:/app/configs:ro
    depends_on:
      - rtl-sdr
    environment:
      - RTL_TCP_HOST=rtl-sdr
      - RTL_TCP_PORT=1234
      - PROCESSING_INTERVAL=60
    restart: unless-stopped
    networks:
      - satx-network

  dashboard:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: satx-dashboard
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs:ro
      - ./recordings:/app/recordings:ro
    depends_on:
      - processor
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    networks:
      - satx-network

networks:
  satx-network:
    driver: bridge
